services:
  app:
    build: ./backend
    ports:
      - "8000:8000"  # Map host port 80 to container port 8000
    volumes:
      - ./backend:/app
      - ./frontend:/app/frontend
      - ./.env:/app/.env
    restart: unless-stopped

