services:
  app:
    build: ./backend
    ports:
      - "8000:8000"  # Map host port 80 to container port 8000
    volumes:
      - ./backend:/app
      - ./frontend:/app/frontend
      - ./.env:/app/.env
    restart: unless-stopped
    networks:
      - app_network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certificates/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

